"""
Hyperoctahedral symmetry of the binary cube {0,1}^n.

The B_3 property is invariant under the hyperoctahedral group B_n acting on
{0,1}^n, generated by:

  * **coordinate permutations**  x -> (x_{pi(0)}, ..., x_{pi(n-1)}), and
  * **coordinate complementations**  x_i -> 1 - x_i on any subset of coordinates.

Both preserve threefold-sum distinctness: a permutation permutes the coordinates
of every sum identically, and complementing coordinate i shifts that coordinate of
every threefold sum by the constant 3, so all sums stay pairwise distinct. The
complementation subgroup alone is exactly "XOR by a fixed mask", so **every B_3 set
can be translated (via complementations) to contain the origin 0** -- the reduction
the branch-and-bound uses to divide the search by up to 2^n.

|B_n| = n! * 2^n. Full canonicalization enumerates the whole group and returns the
lexicographically minimal image; it is used to canonicalize/dedup witnesses and
small enumerations. For n up to 7 that is 645120 group elements, so full
canonicalization is guarded by ``max_group`` and callers pass small sets.
"""
from __future__ import annotations

import itertools
from typing import Iterable, Sequence

Vector = tuple[int, ...]


def translate_to_origin(S: Iterable[Sequence[int]]) -> list[Vector]:
    """
    XOR every vector by the first one so that 0 is a member (identity if S empty).

    This is a hyperoctahedral symmetry (a product of coordinate complementations),
    hence B_3-preserving. WLOG any nonempty B_3 set contains the origin.
    """
    pts = [tuple(int(x) for x in v) for v in S]
    if not pts:
        return []
    mask = pts[0]
    return [tuple(v[i] ^ mask[i] for i in range(len(v))) for v in pts]


def apply_symmetry(S: Sequence[Sequence[int]], perm: Sequence[int], comp: int) -> list[Vector]:
    """Apply coordinate permutation ``perm`` then complement mask ``comp`` (a bitmask)."""
    out: list[Vector] = []
    n = len(perm)
    for v in S:
        out.append(tuple(v[perm[i]] ^ ((comp >> i) & 1) for i in range(n)))
    return out


def canonical_form(
    S: Iterable[Sequence[int]],
    n: int,
    *,
    max_group: int = 700_000,
) -> tuple[Vector, ...]:
    """
    Lexicographically minimal image of S under the hyperoctahedral group B_n.

    Returns a canonical, sorted tuple-of-tuples that is identical for any two sets
    related by a bit-permutation + complementation. Two B_3 sets with the same
    canonical form are "the same" record up to symmetry.

    Guard: if |B_n| = n! * 2^n exceeds ``max_group`` the full sweep is skipped and
    a cheaper normal form (origin-translated, column-sorted, row-sorted) is
    returned -- still a genuine invariant-preserving normalization, just not proven
    globally minimal.
    """
    pts = [tuple(int(x) for x in v) for v in S]
    if not pts:
        return tuple()

    group_size = _factorial(n) * (2 ** n)
    if group_size > max_group:
        return _cheap_normal_form(pts, n)

    best: tuple[Vector, ...] | None = None
    for perm in itertools.permutations(range(n)):
        for comp in range(2 ** n):
            img = apply_symmetry(pts, perm, comp)
            cand = tuple(sorted(img))
            if best is None or cand < best:
                best = cand
    assert best is not None
    return best


def _cheap_normal_form(pts: list[Vector], n: int) -> tuple[Vector, ...]:
    """Origin-translate, then order columns by descending column-sum, then sort rows."""
    tr = translate_to_origin(pts)
    if n == 0:
        return tuple(sorted(tr))
    col_sums = [sum(v[i] for v in tr) for i in range(n)]
    order = sorted(range(n), key=lambda i: (-col_sums[i], i))
    permuted = [tuple(v[order[i]] for i in range(n)) for v in tr]
    return tuple(sorted(permuted))


def _factorial(n: int) -> int:
    r = 1
    for i in range(2, n + 1):
        r *= i
    return r
